
    <div class="messages">
        <?php require("validation-errors.php"); ?>
        <?php require("flash-message.php"); ?>
    </div>

    <div class="main">
        <h2>Add Role</h2>
        
        <form action="/roles/save" method="post" enctype="multipart/form-data">
            <fieldset>
                <table cellspacing="1" cellpadding="3" class="form-entry">
                    <tr>
                        <td class="label">
                            <?php echo $this->form->name->label; ?>
                        </td>
                        <td class="entry">
                            <?php echo $this->form->name; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <?php echo $this->form->permission->label; ?>
                        </td>
                        <td class="entry">
                            <?php echo $this->form->permission; ?>
                        </td>
                    </tr>
                </table>
                
                <div class="form-toolbar">
                    <button type="submit">Save Role</button>
                </div>
            </fieldset>
        </form>
    </div>
    
    <div class="sidebar">
        <h3>Quick Actions</h3>
        
        <a href="/roles">
            <img alt="search" src="/images/icons/magnifier.png" title="Search Roles" /></a>
        <a href="/roles">Search Roles</a>
    </div>