
    <div class="main">
    	<h2>View Roles</h2>
        
        <div class="messages">
            <?php require("validation-errors.php"); ?>
            <?php require("flash-message.php"); ?>
        </div>
        
        <table style="width: 100%;">
            <tr>
                <td style="text-align: right; width: 18%;">
                    Name: 
                </td>
                <td>
                    <?php echo $this->record->name; ?>
                </td>
            </tr>
            
            <tr>
                <td style="text-align: right;">
                    Permission:
                </td>
                <td class="entry">
                    <?php echo $this->record->permission; ?>
                </td>
            </tr>    
        </table>
    </div>
    
    <div class="sidebar">
        <h3>Quick Actions</h3>
        
        <?php $this->quickLink('/roles/edit/' . $this->record->role_id, 'Edit Role',
            QuickLinkHelper::IconEdit); ?>
        <?php $this->quickLink('/roles', 'Search Roles', QuickLinkHelper::IconSearch); ?>
    </div>
