
    <div class="messages">
        <?php require("validation-errors.php"); ?>
        <?php require("flash-message.php"); ?>
    </div>

    <div class="main">
    	<h2>View Roles</h2>
        
        <table style="width: 100%;">
            <tr>
                <td style="text-align: right; width: 18%;">
                    Name: 
                </td>
                <td>
                    <?php echo $this->record->name; ?>
                </td>
            </tr>
            
            <tr>
                <td style="text-align: right;">
                    Permission:
                </td>
                <td class="entry">
                    <?php echo $this->record->permission; ?>
                </td>
            </tr>    
        </table>
    </div>
    
    <div class="sidebar">
        <h3>Quick Actions</h3>
        
        <a href="/roles/edit/<?php echo $this->record->role_id; ?>">
            <img alt="edit" src="/images/icons/silk/page_white_edit.png" title="Edit Role" /></a>
        <a href="/roles/edit/<?php echo $this->record->role_id; ?>">
            Edit Role</a>
    </div>
