
    <?php $this->pageHeader("Edit User", "Search Users", "/users", '/images/zoom.png'); ?>

    <?php require("validation-errors.php"); ?>
    <?php require("flash-message.php"); ?>


    <form action="/users/save" method="post" enctype="multipart/form-data">
        <fieldset>
            <?php echo $this->form->user_id; ?>

            <table cellspacing="1" cellpadding="3" class="form-entry">
                <tr>
                    <td class="label">
                        <?php echo $this->form->first_name->label; ?>
                    </td>
                    <td class="entry">
                        <?php echo $this->form->first_name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <?php echo $this->form->last_name->label; ?>
                    </td>
                    <td class="entry">
                        <?php echo $this->form->last_name; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <?php echo $this->form->email_address->label; ?>
                    </td>
                    <td class="entry">
                        <?php echo $this->form->email_address; ?>
                    </td>
                </tr>
            </table>
            
            <div class="form-toolbar">
                <button type="submit">Save User</button>
            </div>
        </fieldset>
    </form>
