
    <div class="main">
        <h2>Search Users</h2>
        
        	<form method="get" action="/users/paginate/1">
        		<input type="hidden" name="sort" value="<?php echo $this->search->sSort; ?>" />
        		<input type="hidden" name="order" value="<?php echo $this->search->sOrder; ?>" />
        		
        		<table class="data-filters" cellpadding="3" cellspacing="1">
        			<tr>
        				<td>
                            <?php echo $this->form->search_last_name->label; ?>
                        </td>
        				<td>
                            <?php echo $this->form->search_last_name; ?>
        				</td>
        			
        				<td>
                            <?php echo $this->form->search_email_address->label; ?>
                        </td>
        				<td>
                            <?php echo $this->form->search_email_address; ?>
        				</td>
        			
        				<td>
                            <?php echo $this->form->search_status->label; ?>
                        </td>
        				<td>
                            <?php echo $this->form->search_status; ?>
        				</td>
        			
        				<td>
        					<button type="submit">Filter</button>
        				</td>
        			</tr>
        		</table>
        	</form>
            
        	<table class="data-table" cellpadding="4" cellspacing="1">
        		<tr class="header">
        			<td style="width: 25%;">
        				<a href="/users/paginate/1/<?php
        					echo $this->search->SortableColumnString("last_name"); ?>">Name</a>
        			</td>
        			
        			<td style="width: 30%;">
        				<a href="/users/paginate/1/<?php
        					echo $this->search->SortableColumnString("email_address"); ?>">E-mail</a>
        			</td>
        			
        			<td style="width: 15%;">
        				<a href="/users/paginate/1/<?php
        					echo $this->search->SortableColumnString("status"); ?>">Status</a>
        			</td>
        		</tr>
        		
        		<?php foreach($this->search->results as $count => $result): ?>
        		<tr class="row<?php echo $count % 2; ?>">
        			<td>
                        <a href="/users/view/<?php echo $result->user_id; ?>">
        				    <?php echo $result->last_name; ?>, 
                            <?php echo $result->first_name; ?></a>
        			</td>
        			
        			<td>
        				<?php echo $result->email_address; ?>
        			</td>
        			
        			<td>
        				<?php echo ucwords($result->status); ?>
        			</td>
        		</tr>
        		<?php endforeach; ?>
        		
        		<?php if(count($this->search->results) == 0): ?>
        		<tr>
        			<td class="no-results" colspan="4">
        				No Results Found
        			</td>
        		</tr>
        		<?php endif; ?>
        		
        		<?php require("pagination-partial.php"); ?>
        	</table>
    </div>
    
    <div class="sidebar">
        <h3>Quick Actions</h3>
        
        <?php $this->quickLink('/users/add', 'Add User', QuickLinkHelper::IconAdd); ?>
    </div>
