<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?php echo isset($this->title) ? $this->title . " - My Application" : "My Application"; ?></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />
</head>
<body>

    <div class="header">
        <div class="document">
            <h1 class="logo">OpenAvanti Skeleton</h1>
            
            <div class="user">
                <img alt="user" src="/images/icons/user.png" />
                Welcome, <strong><?php echo Authenticator::$user->first_name . " " .
                    Authenticator::$user->last_name; ?></strong> <br />
                <a href="/account">My Account</a> | <a href="/login/destroy">Logout</a>
            </div>
            
            <div class="main-menu top-menu">
                <?php echo $this->menuRenderer('mainMenu'); ?>
            </div>
            
            <div class="admin-menu top-menu">
                <?php echo $this->menuRenderer('adminMenu'); ?>
            </div>
            
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="body">
        <div class="document">
            <?php $this->renderContent(); ?>
            
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="footer">
        <div class="document">
            Copyright &copy; <?php echo date("Y"); ?> My Company. All Rights Reserved.
        </div>
    </div>

</body>
</html>
