<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?php echo isset($this->title) ? $this->title . " - My Application" : "My Application"; ?></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />
</head>
<body>

    <div class="document">
        <div class="header">
            OpenAvanti Skeleton
            
            <div class="menu">
                <ul>
                    <li>
                        <a href="/users">Users</a>
                    </li>
                    <li>
                        <a href="/roles">Roles</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="body">
            <?php $this->renderContent(); ?>
        </div>
        <div class="footer">
            Copyright &copy; <?php echo date("Y"); ?> My Company
        </div>
    </div>

</body>
</html>